### PR TITLE
Netcode mess

### PR DESCRIPTION
**Pull request by JordanPippy**
Please have a look at this before we do something nutty like merge it

### CODE REVIEW

**Comment by Someone5954** [comment]
I'ma warn ya, I have 0 clue what I'm doing

**Comment by JordanPippy** [comment]
> I'ma warn ya, I have 0 clue what I'm doing

Sounds like an ooga booga merge to me

**Comment by Someone5954** [comment]
There's nothing more I want to do than to press the big green button and watch the world burn.

**Review by Someone5954 — APPROVED** [review]
Looks good to me

**Pull request merged**
